<?php

namespace StaffBundle\Entity\Repository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEmailsForNotification()
    {
        $result = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e.email')
            ->from('StaffBundle:Employee', 'e')
            ->getQuery()
            ->getArrayResult();

        return array_column($result, 'email');
    }
}
